# Generated by Django 4.1.2 on 2024-06-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('pswd', models.CharField(max_length=100)),
            ],
        ),
    ]
