# Generated by Django 4.1.2 on 2024-06-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pswd',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
