# Generated by Django 4.1.2 on 2024-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_rename_pswd_usuario_password_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dv',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
