# Generated by Django 4.1.2 on 2024-06-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=6)),
                ('cantidad', models.CharField(max_length=4)),
            ],
        ),
    ]
