# Generated by Django 4.1.2 on 2024-06-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0008_producto_descripcion_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
