# Generated by Django 4.1.2 on 2024-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0009_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
